name: pregnancy_chatbot
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0  
  intl: ^0.18.1
  provider: ^6.0.5
  uuid: ^3.0.7 
  flutter_dotenv: ^5.1.0  # For storing API keys securely 
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  permission_handler: ^11.3.1
  flutter_markdown: ^0.6.18
  firebase_core: ^3.13.1
  cloud_firestore: ^5.4.4
  device_info_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - .env 
    - assets/images/
    - assets/weekimage/
    - assets/weekimage/week-1.jpg
    - assets/weekimage/week-2.jpg
    - assets/weekimage/week-3.jpg
    - assets/weekimage/week-4.jpg
    - assets/weekimage/week-5.jpg
    - assets/weekimage/week-6.jpg
    - assets/weekimage/week-7.jpg
    - assets/weekimage/week-8.jpg
    - assets/weekimage/week-9.jpg
    - assets/weekimage/week-10.jpg
    - assets/weekimage/week-11.jpg
    - assets/weekimage/week-12.jpg
    - assets/weekimage/week-13.jpg
    - assets/weekimage/week-14.jpg
    - assets/weekimage/week-15.jpg
    - assets/weekimage/week-16.jpg
    - assets/weekimage/week-17.jpg
    - assets/weekimage/week-18.jpg
    - assets/weekimage/week-19.jpg
    - assets/weekimage/week-20.jpg
    - assets/weekimage/week-21.jpg
    - assets/weekimage/week-22.jpg
    - assets/weekimage/week-23.jpg
    - assets/weekimage/week-24.jpg
    - assets/weekimage/week-25.jpg
    - assets/weekimage/week-26.jpg
    - assets/weekimage/week-27.jpg  
    - assets/weekimage/week-28.jpg
    - assets/weekimage/week-29.jpg
    - assets/weekimage/week-30.jpg
    - assets/weekimage/week-31.jpg
    - assets/weekimage/week-32.jpg
    - assets/weekimage/week-33.jpg
    - assets/weekimage/week-34.jpg
    - assets/weekimage/week-35.jpg
    - assets/weekimage/week-36.jpg
    - assets/weekimage/week-37.jpg
    - assets/weekimage/week-38.jpg
    - assets/weekimage/week-39.jpg
    - assets/weekimage/week-40.jpg